### ISSUE TITLE
Method function_provider of the Graph class Graph isn't working correctly

### ISSUE THREAD

**Issue by eliostvs** [msiedlarek/wiring#3]
For example, If you try to get the _singleton_ object in the test tests.all.configuration_tests.ModuleTest.test:

```
> graph = Graph()
> module = SomeModule()
> module.add_to(graph)
> graph.get('singleton')
*** TypeError: argument of type 'type' is not iterable
```

This code is broken too:

```
> graph.register_scope(SingletonScope, SingletonScope())
> graph.register_provider'singleton', FactoryProvider(SomeClass, scope=SingletonScope))
> graph.get('singleton')
*** TypeError: argument of type 'type' is not iterable
```

The _function_provider_ should changes the scope of the factory provider by its own before registering it, right?

**Comment by msiedlarek** [comment]
Another great catch, thanks! This is significant enough that I want to release a patch version. I'll do some of my own testing and probably release the patched version around Thursday. If you'll happen to find more problems be sure to let me know - I really appreciate the input.

**Comment by eliostvs** [comment]
Great! Thank you.

**Comment by eliostvs** [comment]
I've created a project in [Opensuse Build Service](https://build.opensuse.org/package/show/home:eliostvs:wiring/python-wiring) with Fedora, Opensuse and Ubuntu repositories. When you release a new version please let me know. Thanks.

**Comment by msiedlarek** [comment]
New version - 0.2.1 - has been released just now.

**Comment by eliostvs** [comment]
Wow. That was quick. Thanks! I've been using wiring in my own [project](https://github.com/eliostvs/tomate) and I 'm really liking.
